### ISSUE TITLE
Constants.hpp missing

### ISSUE THREAD

**Issue by larswd** [trylaarsdam/STM32L4xx-Watchdog#1]
Hi
I am considering making a modified version of your watchdog implementation for a STM32WL-board, and I noticed that you include a "Constants.hpp" file in your "WathDog.hpp" file. is this an unstated dependency, or an unpushed file? If the latter, what is the important parameters you set in your constants.hpp file?

**Comment by trylaarsdam** [comment]
That file was a remnant of the program I was writing when I created this library- it isn't used for anything in this library.
